### ISSUE TITLE
total number of possible markers

### ISSUE THREAD

**Issue by francescoStrada** [shawnlehner/ARMaker#1]
Hello, is it possible to know what is the exact number of possible unique markers?

Thankyou very much.

Regars,

Francesco Strada

**Comment by shawnlehner** [comment]
Hi @francescoStrada, sorry for taking so long to follow-up on this. I haven't been working on this project in a while.

It really depends on what you need. There are technically 3.9402006196394479212279040100144e+115 unique combinations based on the number of pixels used to generate the base marker image. However, the strategy used currently cannot guarantee every version will be absolutely unique because it simply seeds a RNG and then uses that to decide which pixels should be filled in. If you need truly unique markers I would suggest a different generation technique.

If you need to enforce uniqueness I would probably take advantage of the .NET Guid implementation and map those to the pixels. This way you can rely on the uniqueness of the Guid algorithm to ensure no two markers are the same.
